[package]
name = "rpiboot_rs_lib"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies.rusb]
version = "0.9.4"

[dependencies.nusb]
version = "0.2.0"

[dependencies.tar]
version = "0.4.44"

[dependencies.anyhow]
version = "1.0.99"